# Generated by Django 5.2.4 on 2025-07-16 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField(verbose_name='콘텐츠 ID')),
                ('title', models.CharField(max_length=200, verbose_name='방문지 이름')),
                ('first_image', models.URLField(blank=True, max_length=512, null=True, verbose_name='대표 이미지 URL')),
                ('addr1', models.CharField(blank=True, max_length=255, null=True, verbose_name='주소')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='개요')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='북마크 생성 시각')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '북마크',
                'verbose_name_plural': '북마크 목록',
                'db_table': 'users_bookmark',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'content_id')},
            },
        ),
    ]
