# Generated by Django 5.2.4 on 2025-08-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='recommend_reason',
        ),
        migrations.RemoveField(
            model_name='visitedcontent',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='visitedcontent',
            name='recommend_reason',
        ),
    ]
