# Generated by Django 5.2.4 on 2025-08-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_bookmark_hashtags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='hashtags',
            field=models.TextField(blank=True, null=True, verbose_name='해시태그'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='recommend_reason',
            field=models.TextField(blank=True, null=True, verbose_name='추천이유'),
        ),
        migrations.AddField(
            model_name='visitedcontent',
            name='hashtags',
            field=models.TextField(blank=True, null=True, verbose_name='해시태그'),
        ),
        migrations.AddField(
            model_name='visitedcontent',
            name='recommend_reason',
            field=models.TextField(blank=True, null=True, verbose_name='추천이유'),
        ),
    ]
