# Generated by Django 5.2.5 on 2025-08-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_bookmark_hashtags_bookmark_recommend_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitedcontent',
            name='category',
            field=models.TextField(blank=True, null=True, verbose_name='카테고리'),
        ),
    ]
