# Generated by Django 5.2.5 on 2025-08-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_visitedcontent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='category',
            field=models.TextField(blank=True, null=True, verbose_name='카테고리'),
        ),
    ]
