# Generated by Django 5.2.5 on 2025-08-26 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_bookmark_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_path', models.CharField(default='Android', max_length=100, verbose_name='취득경로')),
                ('provided_service', models.CharField(max_length=200, verbose_name='제공 서비스')),
                ('recipient', models.CharField(default='한국관광공사 TOUR_API', max_length=200, verbose_name='제공받는 자')),
                ('usage_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='이용일시')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='대상 (사용자)')),
            ],
            options={
                'verbose_name': '위치정보 이용·제공 기록',
                'verbose_name_plural': '위치정보 이용·제공 기록 (취급대장)',
                'db_table': 'location_usage_log',
                'ordering': ['-usage_timestamp'],
            },
        ),
    ]
